baseURL: "https://claydav.is/" 
title: Clay Davis
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: clay_cd

taxonomies:
    tag: tags
    category: categories
    
menu:
    main:
        - name: Publications
          url: /publications/
          weight: 1
        - name: CV
          url: /cv.pdf
          weight: 2
        - name: Syllabi
          url: /syllabi/
          weight: 3
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=ZuazMDwAAAAJ
          weight: 4

params:
    description: "I am a PhD candidate in sociology and Mellon Cluster Fellow in science studies at Northwestern University."
    author: Clay Davis
    googleAnalyticsID: ""
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Clay Davis
          subtitle: "I am a PhD candidate in sociology and Mellon Cluster Fellow in science studies at Northwestern University. I study the way experts<code>&#8212;</code>both lay and credentialed<code>&#8212;</code>construct their expertise and resolve epistemic conflicts. In particular, I am attuned to the way these actors use and revise methodological tools like randomized controlled trials (see my first paper in <i><a href='/3S1'>Social Studies of Science</a></i>) and meta-analysis (as I explore in my dissertation) in service of these goals."
          imageUrl: "/picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Clay Davis
          buttons:
            - name: Publications
              url: /publications/
            - name: CV
              url: /cv.pdf
            - name: Syllabi
              url: /syllabi/
            - name: Google Scholar
              url: https://scholar.google.com/citations?hl=en&user=ZuazMDwAAAAJ


    socialIcons:
        - name: Email
          url: mailto:cdavis@u.northwestern.edu
        - name: Office Hours
          url: /officehours/
        - name: twitter
          url: https://twitter.com/clay_cd
        
    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Clay Davis"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
