baseURL: "https://claydav.is/" 
title: Clay Davis
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

social:
    twitter: clay_cd

taxonomies:
    tag: tags

menu:
    main:
        - name: Publications
          url: /publications/
          weight: 1
        - name: CV
          url: /cv.pdf
          weight: 2
        - name: Courses
          url: /courses/
          weight: 3


params:
    description: "I am a PhD candidate in sociology and Mellon Cluster Fellow in science studies at Northwestern University."
    author: Clay Davis
    googleAnalyticsID: "G-1GWPQVMT3F"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Clay Davis
          subtitle: "I am PhD candidate in sociology and Mellon Cluster Fellow in science studies at Northwestern University."
          imageUrl: "/picture.jpeg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Clay Davis
          buttons:
            - name: Publications
              url: /publications/
            - name: Courses
              url: /courses/
            - name: CV
              url: /cv.pdf

    socialIcons:
        - name: Email
          url: mailto:cdavis@u.northwestern.edu
        - name: Office Hours
          url: /officehours/
        - name: Google Scholar
          url: https://scholar.google.com/citations?hl=en&user=ZuazMDwAAAAJ

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Clay Davis"
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: xcode
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

# max number of characters:
# * title: 70
# * description: 120–155
# * summary: 265
